# Generated by Django 4.2.18 on 2025-05-05 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0002_customer_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventowner',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
